#! /bin/bash
KEYCHAIN=/Users/`whoami`/Library/Keychains/login.keychain
PAYLOADDIR=/tmp/ggsewifipayload

# Turn off Airport
networksetup -setairportpower en1 off

# Delete the wireless cert.
security delete-cert -c wireless.education.ucsb.edu 2>/dev/null

# Delete all GGSE related wifi profiles
networksetup -listalluserprofiles | while read i; do
	i="\"$i\""
	echo $i | grep -i 'ggse'
	if [ $? == 0 ]; then
		networksetup -deleteuserprofile "$i"
	fi
done

# Re-import the certificate with the correct trust settings
security add-trusted-cert -k $KEYCHAIN -r trustAsRoot -p eap $PAYLOADDIR/wireless.education.ucsb.edu.cer

# Re-import profile

networksetup -import8021xProfiles AirPort $PAYLOADDIR/ggse_bare_profile.networkConnect

# Cleanup tmp files
#rm -rf $PAYLOADDIR

# Turn on Airport
networksetup -setairportpower en1 on
